package com.qa.application.models.eRecords;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.qa.application.models.inspection.Inspection;
import com.qa.application.models.user.User;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

import java.util.HashSet;
import java.util.Set;

/* E.Records will have autogenerated id, firstname, lastname, occupation, address, mobile number
* E.Records will have bidirectional @OneToOne relationship with User
* E.Records will have bidirectional @ManyToMany relationship with Inspections so both sides will be able to get a list of each other
*
* */
@Entity
@Table(name = "employee_records")
public class EmployeeRecords {

    @Id
    @GeneratedValue
    private Integer id;
    @NotBlank()
    private String firstname;
    @NotBlank
    private String lastname;
    @NotBlank
    private String occupation;
    @NotBlank
    private String address;
    @NotBlank
    private String mobileNumber;

    @JsonIgnore
    @OneToOne
    @JoinColumn(name = "user_id")
    private User user;

    @JsonIgnore
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "employee_inspection",
            joinColumns = {@JoinColumn(name = "employee_records_id")},
            inverseJoinColumns = {@JoinColumn(name = "inspection_id")})
    private Set<Inspection> inspections = new HashSet<>();



    public EmployeeRecords(){}

    public EmployeeRecords(String firstname, String lastname, String occupation, String address, String mobileNumber, User user, Set<Inspection> inspections){
        this.firstname = firstname;
        this.lastname = lastname;
        this.occupation = occupation;
        this.address = address;
        this.mobileNumber = mobileNumber;
        this.user = user;
        this.inspections = inspections;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getOccupation() {
        return occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public User getUser() {
        return user;
    }

    public Set<Inspection> getInspections() {
        return inspections;
    }

    public void setInspections(Set<Inspection> inspections) {
        this.inspections = inspections;
    }

    public void setUser(User user) {
        this.user = user;


    }
}
